#!/usr/bin/env bash

set -Eeuxo pipefail

    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-bullseye' \
      --file lua-5.4/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-buster' \
      --file lua-5.4/buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye' \
      --file lua-5.4/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-buster' \
      --file lua-5.4/luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3' \
      --file lua-5.4/alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.16' \
      --file lua-5.4/alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3' \
      --file lua-5.4/luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.16' \
      --file lua-5.4/luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-jammy' \
      --file lua-5.4/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-focal' \
      --file lua-5.4/focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy' \
      --file lua-5.4/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-focal' \
      --file lua-5.4/luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-bullseye' \
      --file lua-5.3/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-buster' \
      --file lua-5.3/buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye' \
      --file lua-5.3/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-buster' \
      --file lua-5.3/luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3' \
      --file lua-5.3/alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.16' \
      --file lua-5.3/alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3' \
      --file lua-5.3/luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.16' \
      --file lua-5.3/luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-jammy' \
      --file lua-5.3/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-focal' \
      --file lua-5.3/focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy' \
      --file lua-5.3/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-focal' \
      --file lua-5.3/luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-bullseye' \
      --file lua-5.2/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-buster' \
      --file lua-5.2/buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye' \
      --file lua-5.2/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-buster' \
      --file lua-5.2/luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3' \
      --file lua-5.2/alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.16' \
      --file lua-5.2/alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3' \
      --file lua-5.2/luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.16' \
      --file lua-5.2/luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-jammy' \
      --file lua-5.2/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-focal' \
      --file lua-5.2/focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy' \
      --file lua-5.2/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-focal' \
      --file lua-5.2/luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-bullseye' \
      --file luajit-2.1-beta/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-buster' \
      --file luajit-2.1-beta/buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-bullseye' \
      --file luajit-2.1-beta/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-buster' \
      --file luajit-2.1-beta/luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-bullseye' \
      --file luajit-2.1-beta/lua52compat-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-buster' \
      --file luajit-2.1-beta/lua52compat-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-bullseye' \
      --file luajit-2.1-beta/lua52compat-luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-buster' \
      --file luajit-2.1-beta/lua52compat-luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3' \
      --file luajit-2.1-beta/alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-alpine3.16' \
      --file luajit-2.1-beta/alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3' \
      --file luajit-2.1-beta/luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-alpine3.16' \
      --file luajit-2.1-beta/luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3' \
      --file luajit-2.1-beta/lua52compat-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-alpine3.16' \
      --file luajit-2.1-beta/lua52compat-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3' \
      --file luajit-2.1-beta/lua52compat-luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-alpine3.16' \
      --file luajit-2.1-beta/lua52compat-luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-jammy' \
      --file luajit-2.1-beta/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-focal' \
      --file luajit-2.1-beta/focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-jammy' \
      --file luajit-2.1-beta/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-luarocks-focal' \
      --file luajit-2.1-beta/luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-jammy' \
      --file luajit-2.1-beta/lua52compat-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-focal' \
      --file luajit-2.1-beta/lua52compat-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-jammy' \
      --file luajit-2.1-beta/lua52compat-luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-beta-lua52compat-luarocks-focal' \
      --file luajit-2.1-beta/lua52compat-luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-bullseye' \
      --file luajit-2.0/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-buster' \
      --file luajit-2.0/buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-bullseye' \
      --file luajit-2.0/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-buster' \
      --file luajit-2.0/luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-bullseye' \
      --file luajit-2.0/lua52compat-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-buster' \
      --file luajit-2.0/lua52compat-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-bullseye' \
      --file luajit-2.0/lua52compat-luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-buster' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-buster,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-buster' \
      --file luajit-2.0/lua52compat-luarocks-buster/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-alpine3' \
      --file luajit-2.0/alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-alpine3.16' \
      --file luajit-2.0/alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3' \
      --file luajit-2.0/luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-alpine3.16' \
      --file luajit-2.0/luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3' \
      --file luajit-2.0/lua52compat-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-alpine3.16' \
      --file luajit-2.0/lua52compat-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3' \
      --file luajit-2.0/lua52compat-luarocks-alpine3/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3.16' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3.16,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-alpine3.16' \
      --file luajit-2.0/lua52compat-luarocks-alpine3.16/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-jammy' \
      --file luajit-2.0/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-focal' \
      --file luajit-2.0/focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-jammy' \
      --file luajit-2.0/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-luarocks-focal' \
      --file luajit-2.0/luarocks-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-jammy' \
      --file luajit-2.0/lua52compat-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-focal' \
      --file luajit-2.0/lua52compat-focal/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-jammy' \
      --file luajit-2.0/lua52compat-luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-focal' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-focal,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.0-lua52compat-luarocks-focal' \
      --file luajit-2.0/lua52compat-luarocks-focal/Dockerfile \
      .
