FROM alpine:<%= distro_version %>

RUN set -ex \
  && apk add --no-cache --virtual .lua-builddeps \
    ca-certificates \
    curl \
    gcc \
    libc-dev \
    make \
    <% if lang == "lua" -%>
      readline-dev \
      <% if version_minor == "5.1" -%>
        ncurses-dev \
      <% end -%>
    <% end -%>
    <% if variant.include?("luarocks") -%>
      coreutils \
      gnupg \
      unzip \
    <% end -%>
  && curl -fsSL -o /tmp/lua.tar.gz "<%= archive_url %>" \
  && cd /tmp \
  && echo "<%= archive_md5 %> *lua.tar.gz" | md5sum -c - \
  && mkdir /tmp/lua \
  && tar -xf /tmp/lua.tar.gz -C /tmp/lua --strip-components=1 \
  && cd /tmp/lua \
  <% if lang == "luajit" && variant.include?("lua52compat") -%>
    && make CFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT" \
  <% elsif lang == "luajit" || version_minor == "5.0" -%>
    && make \
  <% else -%>
    && make linux \
  <% end -%>
  && make install \
  <% if lang == "luajit" && version.prerelease? -%>
    && ln -s /usr/local/bin/luajit-<%= version_full %> /usr/local/bin/luajit \
  <% end -%>
  <% if variant.include?("luarocks") -%>
    && curl -fsSL -o /tmp/luarocks.tar.gz "https://luarocks.org/releases/luarocks-<%= luarocks_version %>.tar.gz" \
    && curl -fsSL -o /tmp/luarocks.tar.gz.asc "https://luarocks.org/releases/luarocks-<%= luarocks_version %>.tar.gz.asc" \
    && cd /tmp \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "8460980B2B79786DE0C7FCC83FD8F43C2BB3C478" \
    && gpg --batch --verify luarocks.tar.gz.asc luarocks.tar.gz \
    && rm -r "$GNUPGHOME" \
    && mkdir /tmp/luarocks \
    && tar -xf /tmp/luarocks.tar.gz -C /tmp/luarocks --strip-components=1 \
    && cd /tmp/luarocks \
    && ./configure \
    && make \
    && make install \
  <% end -%>
  && apk add --no-network --no-cache --virtual .lua-rundeps \
    <% if lang == "lua" -%>
      readline \
      <% if version_minor == "5.1" -%>
        ncurses-libs \
      <% end -%>
    <% end -%>
    <% if lang == "luajit" -%>
      libgcc \
    <% end -%>
    <% if variant.include?("luarocks") -%>
      ca-certificates \
      coreutils \
      curl \
      unzip \
    <% end -%>
  && apk del --no-network .lua-builddeps \
  && cd / \
  && rm -rf /tmp/lua /tmp/lua.tar.gz \
  <% if variant.include?("luarocks") -%>
    && rm -rf /tmp/luarocks /tmp/luarocks.tar.gz \
    && luarocks --version \
  <% end -%>
  && <%= lang %> -v

CMD ["<%= lang %>"]
