#!/usr/bin/env bash

set -Eeuxo pipefail

    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-bookworm' \
      --file lua-5.4/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-bullseye' \
      --file lua-5.4/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm' \
      --file lua-5.4/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bullseye' \
      --file lua-5.4/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.20' \
      --file lua-5.4/alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.19' \
      --file lua-5.4/alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.20' \
      --file lua-5.4/luarocks-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.19' \
      --file lua-5.4/luarocks-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-noble' \
      --file lua-5.4/noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-jammy' \
      --file lua-5.4/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-noble' \
      --file lua-5.4/luarocks-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-jammy' \
      --file lua-5.4/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-bookworm' \
      --file lua-5.3/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-bullseye' \
      --file lua-5.3/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm' \
      --file lua-5.3/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bullseye' \
      --file lua-5.3/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.20' \
      --file lua-5.3/alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.19' \
      --file lua-5.3/alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.20' \
      --file lua-5.3/luarocks-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.19' \
      --file lua-5.3/luarocks-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-noble' \
      --file lua-5.3/noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-jammy' \
      --file lua-5.3/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-noble' \
      --file lua-5.3/luarocks-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-jammy' \
      --file lua-5.3/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-bookworm' \
      --file lua-5.2/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-bullseye' \
      --file lua-5.2/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm' \
      --file lua-5.2/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bullseye' \
      --file lua-5.2/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.20' \
      --file lua-5.2/alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.19' \
      --file lua-5.2/alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.20' \
      --file lua-5.2/luarocks-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.19' \
      --file lua-5.2/luarocks-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-noble' \
      --file lua-5.2/noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-jammy' \
      --file lua-5.2/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-noble' \
      --file lua-5.2/luarocks-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-jammy' \
      --file lua-5.2/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-bookworm' \
      --file luajit-2.1/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-bullseye' \
      --file luajit-2.1/bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm' \
      --file luajit-2.1/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bullseye' \
      --file luajit-2.1/luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm' \
      --file luajit-2.1/lua52compat-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bullseye' \
      --file luajit-2.1/lua52compat-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm' \
      --file luajit-2.1/lua52compat-luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bullseye' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bullseye,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bullseye' \
      --file luajit-2.1/lua52compat-luarocks-bullseye/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.20' \
      --file luajit-2.1/alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.19' \
      --file luajit-2.1/alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.20' \
      --file luajit-2.1/luarocks-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.19' \
      --file luajit-2.1/luarocks-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.20' \
      --file luajit-2.1/lua52compat-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.19' \
      --file luajit-2.1/lua52compat-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.20' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.20,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.20' \
      --file luajit-2.1/lua52compat-luarocks-alpine3.20/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.19' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.19,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.19' \
      --file luajit-2.1/lua52compat-luarocks-alpine3.19/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-noble' \
      --file luajit-2.1/noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-jammy' \
      --file luajit-2.1/jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-noble' \
      --file luajit-2.1/luarocks-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-jammy' \
      --file luajit-2.1/luarocks-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-noble' \
      --file luajit-2.1/lua52compat-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-jammy' \
      --file luajit-2.1/lua52compat-jammy/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-noble' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-noble,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-noble' \
      --file luajit-2.1/lua52compat-luarocks-noble/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-jammy' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-jammy,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-jammy' \
      --file luajit-2.1/lua52compat-luarocks-jammy/Dockerfile \
      .
