#!/usr/bin/env bash

set -Eeuxo pipefail

    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-trixie' \
      --file lua-5.4/trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-bookworm' \
      --file lua-5.4/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-trixie' \
      --file lua-5.4/luarocks-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-bookworm' \
      --file lua-5.4/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.22' \
      --file lua-5.4/alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-alpine3.21' \
      --file lua-5.4/alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.22' \
      --file lua-5.4/luarocks-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-alpine3.21' \
      --file lua-5.4/luarocks-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-rolling' \
      --file lua-5.4/rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-plucky' \
      --file lua-5.4/plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-rolling' \
      --file lua-5.4/luarocks-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.4-luarocks-plucky' \
      --file lua-5.4/luarocks-plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-trixie' \
      --file lua-5.3/trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-bookworm' \
      --file lua-5.3/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-trixie' \
      --file lua-5.3/luarocks-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-bookworm' \
      --file lua-5.3/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.22' \
      --file lua-5.3/alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-alpine3.21' \
      --file lua-5.3/alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.22' \
      --file lua-5.3/luarocks-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-alpine3.21' \
      --file lua-5.3/luarocks-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-rolling' \
      --file lua-5.3/rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-plucky' \
      --file lua-5.3/plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-rolling' \
      --file lua-5.3/luarocks-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.3-luarocks-plucky' \
      --file lua-5.3/luarocks-plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-trixie' \
      --file lua-5.2/trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-bookworm' \
      --file lua-5.2/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-trixie' \
      --file lua-5.2/luarocks-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-bookworm' \
      --file lua-5.2/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.22' \
      --file lua-5.2/alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-alpine3.21' \
      --file lua-5.2/alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.22' \
      --file lua-5.2/luarocks-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-alpine3.21' \
      --file lua-5.2/luarocks-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-rolling' \
      --file lua-5.2/rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-plucky' \
      --file lua-5.2/plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-rolling' \
      --file lua-5.2/luarocks-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:5.2-luarocks-plucky' \
      --file lua-5.2/luarocks-plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-trixie' \
      --file luajit-2.1/trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-bookworm' \
      --file luajit-2.1/bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-trixie' \
      --file luajit-2.1/luarocks-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-bookworm' \
      --file luajit-2.1/luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-trixie' \
      --file luajit-2.1/lua52compat-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-bookworm' \
      --file luajit-2.1/lua52compat-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-trixie' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-trixie,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-trixie' \
      --file luajit-2.1/lua52compat-luarocks-trixie/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-bookworm' \
      --file luajit-2.1/lua52compat-luarocks-bookworm/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.22' \
      --file luajit-2.1/alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-alpine3.21' \
      --file luajit-2.1/alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.22' \
      --file luajit-2.1/luarocks-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-alpine3.21' \
      --file luajit-2.1/luarocks-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.22' \
      --file luajit-2.1/lua52compat-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-alpine3.21' \
      --file luajit-2.1/lua52compat-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.22' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.22,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.22' \
      --file luajit-2.1/lua52compat-luarocks-alpine3.22/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.21' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.21,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-alpine3.21' \
      --file luajit-2.1/lua52compat-luarocks-alpine3.21/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-rolling' \
      --file luajit-2.1/rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-plucky' \
      --file luajit-2.1/plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-rolling' \
      --file luajit-2.1/luarocks-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-luarocks-plucky' \
      --file luajit-2.1/luarocks-plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-rolling' \
      --file luajit-2.1/lua52compat-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-plucky' \
      --file luajit-2.1/lua52compat-plucky/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-rolling' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-rolling,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-rolling' \
      --file luajit-2.1/lua52compat-luarocks-rolling/Dockerfile \
      .
    docker buildx build \
      --platform 'linux/amd64,linux/arm64' \
      --pull \
      --push \
      --cache-from 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-plucky' \
      --cache-to 'type=registry,ref=ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-plucky,mode=max' \
      --tag 'localhost:5000/ghcr.io/gui/lua-docker-build-cache:2.1-lua52compat-luarocks-plucky' \
      --file luajit-2.1/lua52compat-luarocks-plucky/Dockerfile \
      .
