version: 2.1
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run: ./.circleci/run
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
