version: 2.1
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run: ./.circleci/run
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: ./publish
workflows:
  version: 2
  commit:
    jobs:
      - test
      - publish
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - publish
