#!/usr/bin/env bash

set -Eeuox pipefail

if [ -n "$(git status --porcelain)" ]; then
  echo "Error: Git checkout is not clean before running updates."
  exit 1
fi

./update

if [ -n "$(git status --porcelain)" ]; then
  echo "There are Lua or LuaRocks updates that should be reviewed and committed."
  exit 1
fi
